Ez-BUY/Controllers/BookingCnfsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using OnlineMovieV04.Models;

namespace OnlineMovieV04.Controllers
{
    [Authorize]
    public class BookingCnfsController : Controller
    {
        
        private OnlineMovieTicketEntities db = new OnlineMovieTicketEntities();
        private OnlineMovieTicketEntities bb = new OnlineMovieTicketEntities();

        // GET: BookingCnfs
        public ActionResult Index()
        {
            return View(db.BookingCnfs.ToList());
        }

        // GET: BookingCnfs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingCnf bookingCnf = db.BookingCnfs.Find(id);
            if (bookingCnf == null)
            {
                return HttpNotFound();
            }
            return View(bookingCnf);
        }

        // GET: BookingCnfs/Create
       

        // POST: BookingCnfs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
      
        
        public ActionResult Create([Bind(Include = "UserName,Movie,Id,Price")] BookingCnf bookingCnf)
        {
            if (ModelState.IsValid)
            {
                string mNAme= Session["MName"].ToString();
                string uNAme = Session["Username"].ToString();
               // if (db.BookingCnfs.Any(x=>x.UserName==uNAme&&x.Movie==mNAme ))
                    
                    bookingCnf.Movie = mNAme;
                    bookingCnf.UserName = uNAme;
                    bookingCnf.Price = Convert.ToInt16(Session["Price"]);
                    db.BookingCnfs.Add(bookingCnf);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                

               

            }
            RedirectToAction("Index", "MovieDetails");
            return View(bookingCnf);
        }

        // GET: BookingCnfs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingCnf bookingCnf = db.BookingCnfs.Find(id);
            if (bookingCnf == null)
            {
                return HttpNotFound();
            }
            return View(bookingCnf);
        }

        // POST: BookingCnfs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserName,Movie,Id,Price")] BookingCnf bookingCnf)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookingCnf).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookingCnf);
        }

        // GET: BookingCnfs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingCnf bookingCnf = db.BookingCnfs.Find(id);
            if (bookingCnf == null)
            {
                return HttpNotFound();
            }
            return View(bookingCnf);
        }

        // POST: BookingCnfs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BookingCnf bookingCnf = db.BookingCnfs.Find(id);
            db.BookingCnfs.Remove(bookingCnf);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Payment(int? id)
        {
           if(id ==null)
            {
                 
                return View();
            }
            var movieDetails = bb.MovieDetails.Where(x => x.ID == id).FirstOrDefault();
            Session["MName"] = movieDetails.Name;
            Session["Price"] = movieDetails.Price;
            string mNAme = Session["MName"].ToString();
            string uNAme = Session["Username"].ToString();

            if (db.BookingCnfs.Any(x => x.UserName == uNAme && x.Movie == mNAme))
            {
                //  RedirectToAction("Index", "MovieDetails");
                return RedirectToAction("PaymentCnf");
            }
            return RedirectToAction("PaymentA");


        }
        [HttpPost]
        public ActionResult Payment(string s)
        {
            return RedirectToAction("Create");


        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult PaymentCnf()
        {
 
            return View();
        }
        public ActionResult PaymentA(int? id)
        {
            if (id == null)
            {

                return View();
            }
            var movieDetails = bb.MovieDetails.Where(x => x.ID == id).FirstOrDefault();
            Session["MName"] = movieDetails.Name;
            Session["Price"] = movieDetails.Price;
          //1  BookingCnf bookingCnf=bb.BookingCnfs.Where()

            return View();
        }
        public ActionResult PaymentB()
        {

            return View();
        }
        [HttpPost]
        public ActionResult PaymentB(string s)
        {

            return RedirectToAction("Create");
        }
    }
}

Ez-BUY/Controllers/UserDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineMovieV04.Models;

namespace OnlineMovieV04.Controllers
{
    [Authorize]
    public class UserDetailsController : Controller
    {
        public UserDetailsController()
        {
            
        }
        private OnlineMovieTicketEntities db = new OnlineMovieTicketEntities();

        // GET: UserDetails
        public ActionResult Index()
        {
            return View(db.UserDetails.ToList());
        }

        // GET: UserDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // GET: UserDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,UserName,PhoneNumber,Email,DOB,Password,Role")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                db.UserDetails.Add(userDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userDetail);
        }

        // GET: UserDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // POST: UserDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,UserName,PhoneNumber,Email,DOB,Password,Role")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userDetail);
        }

        // GET: UserDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userDetail = db.UserDetails.Find(id);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            return View(userDetail);
        }

        // POST: UserDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserDetail userDetail = db.UserDetails.Find(id);
            db.UserDetails.Remove(userDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ez-BUY/Views/Shared/ErrorHandel.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ErrorHandel</title>
</head>
<body style="background-image: url('../../loginresource/images/pop.png'); ">

    <h3>PLEASE LOGIN TO CONTINUE</h3>
    <button>
        @Html.ActionLink("lOGIN", "LogIn", "Home");
    </button>



</body>
</html>

Ez-BUY/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/Datepicker.css" rel="stylesheet" />
</head>
<body>
    @if (Session["Username"] == null && Session["Role"] == null)
    {
        Html.RenderPartial("_LogInError");
    }
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Book Easy", "Index", "MovieDetails", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Movie", "Index", "MovieDetails")</li>
                    @if (Session["Role"].ToString() == "admin")
                    {

                        <li>@Html.ActionLink("Users", "Index", "UserDetails")</li>

                    } @if (Session["Role"].ToString() == "User")
                    {
                        <li>@Html.ActionLink("Profile", "UserProfile", "Home")</li>
                    }

                    <li>@Html.ActionLink("DashBord", "Index", "BookingCnfs")</li>

                    <li style="float: right">@Html.ActionLink("LogOut", "LogOut", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        <h1></h1>
        <h1></h1>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - By Tripling Group of ISBR</p>
            @Html.ActionLink("Terms & Condition....", "TermsAndCondition", "Home")
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Ez-BUY/Views/Shared/_LogInError.cshtml
<body style="background-image: url('../../loginresource/images/pop.png'); ">

    <h3>PLEASE LOGIN TO CONTINUE</h3>
    <button>
        @Html.ActionLink("lOGIN", "LogIn", "Home");
    </button>
   

    
</body>